version: "3.8"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
    environment:
      - NODE_ENV=development
